// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsonozmaaqtbztkotgah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzb25vem1hYXF0Ynp0a290Z2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTM3MzUsImV4cCI6MjA2MzgyOTczNX0.MuGQVdk2_YxLB-aydlxVoV9npb85KanfQOwLhBT_PKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);